/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

import "time"

type CalendarGetMyBookings_Variables struct {
	From time.Time `json:"from"`
	To   time.Time `json:"to"`
}

type CalendarGetMyBookings_Data struct {
	Student CalendarGetMyBookings_Data_Student `json:"student"`
}

type CalendarGetMyBookings_Data_Student struct {
	GetMyCalendarBookings []interface{} `json:"getMyCalendarBookings"`
	Typename              string        `json:"__typename"`
}

func (ctx *RequestContext) CalendarGetMyBookings(variables CalendarGetMyBookings_Variables) (CalendarGetMyBookings_Data, error) {
	request := gql.NewQueryRequest[CalendarGetMyBookings_Variables](
		"query calendarGetMyBookings($from: DateTime!, $to: DateTime!) {\n  student {\n    getMyCalendarBookings(from: $from, to: $to) {\n      ...CalendarReviewBooking\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment CalendarReviewBooking on CalendarBooking {\n  id\n  answerId\n  eventSlotId\n  task {\n    id\n    goalId\n    goalName\n    studentTaskAdditionalAttributes {\n      cookiesCount\n      __typename\n    }\n    assignmentType\n    __typename\n  }\n  eventSlot {\n    id\n    start\n    end\n    event {\n      eventUserRole\n      eventCode\n      __typename\n    }\n    school {\n      shortName\n      __typename\n    }\n    __typename\n  }\n  verifierUser {\n    ...CalendarReviewUser\n    __typename\n  }\n  verifiableInfo {\n    verifiableStudents {\n      ...VerifiableStudentItem\n      __typename\n    }\n    team {\n      name\n      __typename\n    }\n    __typename\n  }\n  bookingStatus\n  isOnline\n  vcLinkUrl\n  additionalChecklist {\n    filledChecklistId\n    filledChecklistStatusRecordingEnum\n    __typename\n  }\n  __typename\n}\n\nfragment CalendarReviewUser on User {\n  id\n  login\n  __typename\n}\n\nfragment VerifiableStudentItem on VerifiableStudent {\n  userId\n  login\n  avatarUrl\n  levelCode\n  isTeamLead\n  cookiesCount\n  codeReviewPoints\n  school {\n    shortName\n    __typename\n  }\n  __typename\n}\n",
		variables,
	)

	return GqlRequest[CalendarGetMyBookings_Data](ctx, request)
}
