/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

import "time"

type CalendarGetMyActualP2pRequests_Variables struct {
	From time.Time `json:"from"`
	To   time.Time `json:"to"`
}

type CalendarGetMyActualP2pRequests_Data struct {
	Student CalendarGetMyActualP2pRequests_Data_Student `json:"student"`
}

type CalendarGetMyActualP2pRequests_Data_Student struct {
	GetMyActualP2PRequests []interface{} `json:"getMyActualP2pRequests"`
	Typename               string        `json:"__typename"`
}

func (ctx *RequestContext) CalendarGetMyActualP2pRequests(variables CalendarGetMyActualP2pRequests_Variables) (CalendarGetMyActualP2pRequests_Data, error) {
	request := gql.NewQueryRequest[CalendarGetMyActualP2pRequests_Variables](
		"query calendarGetMyActualP2pRequests($from: DateTime!, $to: DateTime!) {\n  student {\n    getMyActualP2pRequests(from: $from, to: $to) {\n      ...CalendarP2pRequest\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment CalendarP2pRequest on P2pRequest {\n  p2pRequestId\n  startTime\n  endTime\n  isOnline\n  goalId\n  goalName\n  studentAnswerId\n  __typename\n}\n",
		variables,
	)

	return GqlRequest[CalendarGetMyActualP2pRequests_Data](ctx, request)
}
