/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type CalendarDeleteEventSlot_Variables struct {
	EventSlotID string `json:"eventSlotId"`
}

type CalendarDeleteEventSlot_Data struct {
	Student CalendarDeleteEventSlot_Data_Student `json:"student"`
}

type CalendarDeleteEventSlot_Data_Student struct {
	DeleteEventSlot bool   `json:"deleteEventSlot"`
	Typename        string `json:"__typename"`
}

func (ctx *RequestContext) CalendarDeleteEventSlot(variables CalendarDeleteEventSlot_Variables) (CalendarDeleteEventSlot_Data, error) {
	request := gql.NewQueryRequest[CalendarDeleteEventSlot_Variables](
		"mutation calendarDeleteEventSlot($eventSlotId: ID!) {\n  student {\n    deleteEventSlot(eventSlotId: $eventSlotId)\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[CalendarDeleteEventSlot_Data](ctx, request)
}
