/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import (
	"time"

	"github.com/arseniisemenow/s21auto-client-go/gql"
)

type GetCoinsHistory_Variables struct {
}

type GetCoinsHistory_Data struct {
	Student GetCoinsHistory_Data_Student `json:"student"`
}

type GetCoinsHistory_Data_Student struct {
	GetUserCoinsHistory []GetCoinsHistory_Data_GetUserCoinsHistory `json:"getUserCoinsHistory"`
	Typename            string                                     `json:"__typename"`
}

type GetCoinsHistory_Data_GetUserCoinsHistory struct {
	ID                    int64       `json:"id"`
	ItemType              string      `json:"itemType"`
	Amount                int64       `json:"amount"`
	Date                  time.Time   `json:"date"`
	BadgeName             *string     `json:"badgeName"`
	BadgeAvatar           *string     `json:"badgeAvatar"`
	ExternalTransactionID int64       `json:"externalTransactionId"`
	GiverLogin            *string     `json:"giverLogin"`
	Comment               *string     `json:"comment"`
	AmountAfter           int64       `json:"amountAfter"`
	TournamentName        interface{} `json:"tournamentName"`
	Typename              string      `json:"__typename"`
}

func (ctx *RequestContext) GetCoinsHistory(variables GetCoinsHistory_Variables) (GetCoinsHistory_Data, error) {
	request := gql.NewQueryRequest[GetCoinsHistory_Variables](
		"query getCoinsHistory {\n  student {\n    getUserCoinsHistory {\n      ...CoinsTransactionInfo\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment CoinsTransactionInfo on UserCoinsHistoryItemModel {\n  id\n  itemType\n  amount\n  date\n  badgeName\n  badgeAvatar\n  externalTransactionId\n  giverLogin\n  comment\n  amountAfter\n  tournamentName\n  __typename\n}\n",
		variables,
	)

	return GqlRequest[GetCoinsHistory_Data](ctx, request)
}
