/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

import "time"

type GetReviewPointTransactions_Variables struct {
	UserID string    `json:"userId"`
	RpType string    `json:"rpType"`
	From   time.Time `json:"from"`
	To     time.Time `json:"to"`
}

type GetReviewPointTransactions_Data struct {
	School21 GetReviewPointTransactions_Data_School21 `json:"school21"`
}

type GetReviewPointTransactions_Data_School21 struct {
	GetReviewPointTransactions GetReviewPointTransactions_Data_GetReviewPointTransactions `json:"getReviewPointTransactions"`
	Typename                   string                                                     `json:"__typename"`
}

type GetReviewPointTransactions_Data_GetReviewPointTransactions struct {
	LastBalanceBeforePeriod int64         `json:"lastBalanceBeforePeriod"`
	ReviewPointTransactions []interface{} `json:"reviewPointTransactions"`
	Typename                string        `json:"__typename"`
}

func (ctx *RequestContext) GetReviewPointTransactions(variables GetReviewPointTransactions_Variables) (GetReviewPointTransactions_Data, error) {
	request := gql.NewQueryRequest[GetReviewPointTransactions_Variables](
		"query getReviewPointTransactions($userId: UUID!, $rpType: RpType!, $from: DateTime!, $to: DateTime!) {\n  school21 {\n    getReviewPointTransactions(\n      userId: $userId\n      rpType: $rpType\n      from: $from\n      to: $to\n    ) {\n      lastBalanceBeforePeriod\n      reviewPointTransactions {\n        id\n        rpType\n        date\n        isLastTransactionOfDay\n        transactionSource\n        amount\n        amountAfter\n        actionTypeDescription\n        badgeName\n        badgeAvatar\n        projectName\n        projectId\n        verifiableLogin\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[GetReviewPointTransactions_Data](ctx, request)
}
