/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import (
	"time"

	"github.com/arseniisemenow/s21auto-client-go/gql"
)

type GetAsapWidgets_Variables struct {
}

type GetAsapWidgets_Data struct {
	Asap GetAsapWidgets_Data_Asap `json:"ASAP"`
}

type GetAsapWidgets_Data_Asap struct {
	GetASAPMessages []GetAsapWidgets_Data_GetASAPMessage `json:"getASAPMessages"`
	Typename        string                               `json:"__typename"`
}

type GetAsapWidgets_Data_GetASAPMessage struct {
	SmallImageURL  string      `json:"smallImageUrl"`
	SmallTitle     string      `json:"smallTitle"`
	SmallURL       string      `json:"smallUrl"`
	StartDate      time.Time   `json:"startDate"`
	FinishDate     time.Time   `json:"finishDate"`
	ShowFinishDate bool        `json:"showFinishDate"`
	FullTitle      string      `json:"fullTitle"`
	FullText       interface{} `json:"fullText"`
	FullImageURL   string      `json:"fullImageUrl"`
	ADTType        string      `json:"adtType"`
	ADTWidgetID    int64       `json:"adtWidgetId"`
	Typename       string      `json:"__typename"`
}

func (ctx *RequestContext) GetAsapWidgets(variables GetAsapWidgets_Variables) (GetAsapWidgets_Data, error) {
	request := gql.NewQueryRequest[GetAsapWidgets_Variables](
		"query getAsapWidgets {\n  ASAP {\n    getASAPMessages {\n      ...AsapWidget\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment AsapWidget on ASAPMessage {\n  smallImageUrl\n  smallTitle\n  smallUrl\n  startDate\n  finishDate\n  showFinishDate\n  fullTitle\n  fullText\n  fullImageUrl\n  adtType\n  adtWidgetId\n  __typename\n}\n",
		variables,
	)

	return GqlRequest[GetAsapWidgets_Data](ctx, request)
}
