/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetCurrentUserExperience_Variables struct {
}

type GetCurrentUserExperience_Data struct {
	Student GetCurrentUserExperience_Data_Student `json:"student"`
}

type GetCurrentUserExperience_Data_Student struct {
	GetExperience GetCurrentUserExperience_Data_GetExperience `json:"getExperience"`
	Typename      string                                      `json:"__typename"`
}

type GetCurrentUserExperience_Data_GetExperience struct {
	ID               string                              `json:"id"`
	CookiesCount     int64                               `json:"cookiesCount"`
	CodeReviewPoints int64                               `json:"codeReviewPoints"`
	CoinsCount       int64                               `json:"coinsCount"`
	Level            GetCurrentUserExperience_Data_Level `json:"level"`
	Typename         string                              `json:"__typename"`
}

type GetCurrentUserExperience_Data_Level struct {
	ID       int64                               `json:"id"`
	Range    GetCurrentUserExperience_Data_Range `json:"range"`
	Typename string                              `json:"__typename"`
}

type GetCurrentUserExperience_Data_Range struct {
	ID        string `json:"id"`
	LevelCode int64  `json:"levelCode"`
	Typename  string `json:"__typename"`
}

func (ctx *RequestContext) GetCurrentUserExperience(variables GetCurrentUserExperience_Variables) (GetCurrentUserExperience_Data, error) {
	request := gql.NewQueryRequest[GetCurrentUserExperience_Variables](
		"query getCurrentUserExperience {\n  student {\n    getExperience {\n      ...CurrentUserExperience\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment CurrentUserExperience on UserExperience {\n  id\n  cookiesCount\n  codeReviewPoints\n  coinsCount\n  level {\n    id\n    range {\n      id\n      levelCode\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n",
		variables,
	)

	return GqlRequest[GetCurrentUserExperience_Data](ctx, request)
}
