/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetNotificationUserSettings_Variables struct {
}

type GetNotificationUserSettings_Data struct {
	NotificationConfiguration GetNotificationUserSettings_Data_NotificationConfiguration `json:"notificationConfiguration"`
}

type GetNotificationUserSettings_Data_NotificationConfiguration struct {
	Settings []GetNotificationUserSettings_Data_Setting `json:"settings"`
	Typename string                                     `json:"__typename"`
}

type GetNotificationUserSettings_Data_Setting struct {
	GroupTypeID         string `json:"groupTypeId"`
	GroupTypeName       string `json:"groupTypeName"`
	TypeID              string `json:"typeId"`
	TypeName            string `json:"typeName"`
	ChannelID           string `json:"channelId"`
	ChannelName         string `json:"channelName"`
	ChannelActive       bool   `json:"channelActive"`
	ChannelActiveSystem bool   `json:"channelActiveSystem"`
	ChannelLockedSystem bool   `json:"channelLockedSystem"`
	IsMutable           bool   `json:"isMutable"`
	Typename            string `json:"__typename"`
}

func (ctx *RequestContext) GetNotificationUserSettings(variables GetNotificationUserSettings_Variables) (GetNotificationUserSettings_Data, error) {
	request := gql.NewQueryRequest[GetNotificationUserSettings_Variables](
		"query getNotificationUserSettings {\n  notificationConfiguration {\n    settings: getNotificationUserSettings {\n      groupTypeId\n      groupTypeName\n      typeId\n      typeName\n      channelId\n      channelName\n      channelActive\n      channelActiveSystem\n      channelLockedSystem\n      isMutable\n      __typename\n    }\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[GetNotificationUserSettings_Data](ctx, request)
}
