/*
This file was manually created (not auto-generated by s21auto).
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetActiveS21Campuses_Variables struct {
}

type GetActiveS21Campuses_Data struct {
	Query GetActiveS21Campuses_Data_Query `json:"query"`
}

type GetActiveS21Campuses_Data_Query struct {
	GetActiveS21Campuses []GetActiveS21Campuses_Data_SafeSchool `json:"getActiveS21Campuses"`
	Typename             string                                 `json:"__typename"`
}

type GetActiveS21Campuses_Data_SafeSchool struct {
	ID                          string                           `json:"id"`
	FullName                    string                           `json:"fullName"`
	ShortName                   string                           `json:"shortName"`
	OrganizationType            string                           `json:"organizationType"`
	OrganizationTypeId          string                           `json:"organizationTypeId"`
	OrganizationHierarchyTypeId string                           `json:"organizationHierarchyTypeId"`
	Address                     string                           `json:"address"`
	Logo                        string                           `json:"logo"`
	Identifier                  string                           `json:"identifier"`
	Region                      GetActiveS21Campuses_Data_Region `json:"region"`
	Typename                    string                           `json:"__typename"`
}

type GetActiveS21Campuses_Data_Region struct {
	RegionId        string `json:"regionId"`
	DisplayableName string `json:"displayableName"`
	Typename        string `json:"__typename"`
}

func (ctx *RequestContext) GetActiveS21Campuses(variables GetActiveS21Campuses_Variables) (GetActiveS21Campuses_Data, error) {
	request := gql.NewQueryRequest[GetActiveS21Campuses_Variables](
		"query getActiveS21Campuses {\n  getActiveS21Campuses {\n    id\n    fullName\n    shortName\n    organizationType\n    organizationTypeId\n    organizationHierarchyTypeId\n    address\n    logo\n    identifier\n    region {\n      regionId\n      displayableName\n      __typename\n    }\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[GetActiveS21Campuses_Data](ctx, request)
}
