/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetProjectTeamWithMembersByStudent_Variables struct {
	GoalID    string `json:"goalId"`
	StudentID string `json:"studentId"`
}

type GetProjectTeamWithMembersByStudent_Data struct {
	School21 GetProjectTeamWithMembersByStudent_Data_School21 `json:"school21"`
}

type GetProjectTeamWithMembersByStudent_Data_School21 struct {
	GetProjectTeamWithMembers GetProjectTeamWithMembersByStudent_Data_GetProjectTeamWithMembers `json:"getProjectTeamWithMembers"`
	Typename                  string                                                            `json:"__typename"`
}

type GetProjectTeamWithMembersByStudent_Data_GetProjectTeamWithMembers struct {
	TeamWithMembers GetProjectTeamWithMembersByStudent_Data_TeamWithMembers `json:"teamWithMembers"`
	InvitedStudents []interface{}                                           `json:"invitedStudents"`
	Typename        string                                                  `json:"__typename"`
}

type GetProjectTeamWithMembersByStudent_Data_TeamWithMembers struct {
	Team     GetProjectTeamWithMembersByStudent_Data_Team     `json:"team"`
	Members  []GetProjectTeamWithMembersByStudent_Data_Member `json:"members"`
	Typename string                                           `json:"__typename"`
}

type GetProjectTeamWithMembersByStudent_Data_Member struct {
	Role     string                                       `json:"role"`
	User     GetProjectTeamWithMembersByStudent_Data_User `json:"user"`
	Typename string                                       `json:"__typename"`
}

type GetProjectTeamWithMembersByStudent_Data_User struct {
	ID                    string                                                 `json:"id"`
	AvatarURL             string                                                 `json:"avatarUrl"`
	Login                 string                                                 `json:"login"`
	UserExperience        GetProjectTeamWithMembersByStudent_Data_UserExperience `json:"userExperience"`
	ActiveSchoolShortName *string                                                `json:"activeSchoolShortName"`
	Typename              string                                                 `json:"__typename"`
}

type GetProjectTeamWithMembersByStudent_Data_UserExperience struct {
	Level            GetProjectTeamWithMembersByStudent_Data_Level `json:"level"`
	CookiesCount     int64                                         `json:"cookiesCount"`
	CodeReviewPoints int64                                         `json:"codeReviewPoints"`
	Typename         string                                        `json:"__typename"`
}

type GetProjectTeamWithMembersByStudent_Data_Level struct {
	ID       int64                                         `json:"id"`
	Range    GetProjectTeamWithMembersByStudent_Data_Range `json:"range"`
	Typename string                                        `json:"__typename"`
}

type GetProjectTeamWithMembersByStudent_Data_Range struct {
	LevelCode int64  `json:"levelCode"`
	Typename  string `json:"__typename"`
}

type GetProjectTeamWithMembersByStudent_Data_Team struct {
	ID                 string `json:"id"`
	Name               string `json:"name"`
	Status             string `json:"status"`
	MinTeamMemberCount int64  `json:"minTeamMemberCount"`
	MaxTeamMemberCount int64  `json:"maxTeamMemberCount"`
	Typename           string `json:"__typename"`
}

func (ctx *RequestContext) GetProjectTeamWithMembersByStudent(variables GetProjectTeamWithMembersByStudent_Variables) (GetProjectTeamWithMembersByStudent_Data, error) {
	request := gql.NewQueryRequest[GetProjectTeamWithMembersByStudent_Variables](
		"query getProjectTeamWithMembersByStudent($goalId: ID!, $studentId: UUID!) {\n  school21 {\n    getProjectTeamWithMembers(goalId: $goalId, studentId: $studentId) {\n      ...TeamWithMembers\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment TeamWithMembers on ProjectTeamWithMembers {\n  teamWithMembers {\n    team {\n      id\n      name\n      status\n      minTeamMemberCount\n      maxTeamMemberCount\n      __typename\n    }\n    members {\n      ...TeamMemberWithRole\n      __typename\n    }\n    __typename\n  }\n  invitedStudents {\n    student {\n      user {\n        ...ProjectTeamMember\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment TeamMemberWithRole on TeamMember {\n  role\n  user {\n    ...ProjectTeamMember\n    __typename\n  }\n  __typename\n}\n\nfragment ProjectTeamMember on User {\n  id\n  avatarUrl\n  login\n  userExperience {\n    level {\n      id\n      range {\n        levelCode\n        __typename\n      }\n      __typename\n    }\n    cookiesCount\n    codeReviewPoints\n    __typename\n  }\n  activeSchoolShortName\n  __typename\n}\n",
		variables,
	)

	return GqlRequest[GetProjectTeamWithMembersByStudent_Data](ctx, request)
}
