/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetIsApiDocumentationEnabled_Variables struct {
}

type GetIsApiDocumentationEnabled_Data struct {
	Sc21StudentTaskCheck GetIsApiDocumentationEnabled_Data_Sc21StudentTaskCheck `json:"sc21StudentTaskCheck"`
}

type GetIsApiDocumentationEnabled_Data_Sc21StudentTaskCheck struct {
	IsOpenAPIAllowed bool   `json:"isOpenApiAllowed"`
	Typename         string `json:"__typename"`
}

func (ctx *RequestContext) GetIsApiDocumentationEnabled(variables GetIsApiDocumentationEnabled_Variables) (GetIsApiDocumentationEnabled_Data, error) {
	request := gql.NewQueryRequest[GetIsApiDocumentationEnabled_Variables](
		"query getIsApiDocumentationEnabled {\n  sc21StudentTaskCheck {\n    isOpenApiAllowed\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[GetIsApiDocumentationEnabled_Data](ctx, request)
}
