/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

import "time"

type GetAgendaEvents_Variables struct {
	From  time.Time `json:"from"`
	To    time.Time `json:"to"`
	Limit int64     `json:"limit"`
}

type GetAgendaEvents_Data struct {
	CalendarEventS21 GetAgendaEvents_Data_CalendarEventS21 `json:"calendarEventS21"`
}

type GetAgendaEvents_Data_CalendarEventS21 struct {
	GetMyAgendaEvents []interface{} `json:"getMyAgendaEvents"`
	Typename          string        `json:"__typename"`
}

func (ctx *RequestContext) GetAgendaEvents(variables GetAgendaEvents_Variables) (GetAgendaEvents_Data, error) {
	request := gql.NewQueryRequest[GetAgendaEvents_Variables](
		"query getAgendaEvents($from: DateTime!, $to: DateTime!, $limit: Int!) {\n  calendarEventS21 {\n    getMyAgendaEvents(from: $from, to: $to, limit: $limit) {\n      agendaItemContext {\n        entityId\n        entityType\n        __typename\n      }\n      start\n      end\n      label\n      description\n      agendaEventType\n      additionalInfo {\n        key\n        value\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[GetAgendaEvents_Data](ctx, request)
}
