/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetSaleProgressPercentages_Variables struct {
}

type GetSaleProgressPercentages_Data struct {
	School21 GetSaleProgressPercentages_Data_School21 `json:"school21"`
}

type GetSaleProgressPercentages_Data_School21 struct {
	GetSaleProgressPercentages []interface{} `json:"getSaleProgressPercentages"`
	Typename                   string        `json:"__typename"`
}

func (ctx *RequestContext) GetSaleProgressPercentages(variables GetSaleProgressPercentages_Variables) (GetSaleProgressPercentages_Data, error) {
	request := gql.NewQueryRequest[GetSaleProgressPercentages_Variables](
		"query getSaleProgressPercentages {\n  school21 {\n    getSaleProgressPercentages {\n      ...RpSaleInfo\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment RpSaleInfo on RpSaleProgress {\n  rpType\n  progressPercentage\n  __typename\n}\n",
		variables,
	)

	return GqlRequest[GetSaleProgressPercentages_Data](ctx, request)
}
