/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetRecommendedProjects_Variables struct {
	UserID string `json:"userId"`
}


type GetRecommendedProjects_Data struct {
	Student GetRecommendedProjects_Data_Student `json:"student"`
}

type GetRecommendedProjects_Data_Student struct {
	GetRecommendedProjects []GetRecommendedProjects_Data_GetRecommendedProject `json:"getRecommendedProjects"`
	Typename               string                  `json:"__typename"`
}

import "time"

type GetRecommendedProjects_Data_GetRecommendedProject struct {
	GoalID                         *int64      `json:"goalId"`
	Name                           string      `json:"name"`
	Description                    string      `json:"description"`
	Experience                     int64       `json:"experience"`
	DateTime                       *time.Time  `json:"dateTime"`
	FinalPercentage                interface{} `json:"finalPercentage"`
	Laboriousness                  int64       `json:"laboriousness"`
	ExecutionType                  *string     `json:"executionType"`
	GoalStatus                     *string     `json:"goalStatus"`
	CourseType                     *string     `json:"courseType"`
	DisplayedCourseStatus          *string     `json:"displayedCourseStatus"`
	AmountAnswers                  interface{} `json:"amountAnswers"`
	AmountMembers                  interface{} `json:"amountMembers"`
	AmountJoinedMembers            interface{} `json:"amountJoinedMembers"`
	AmountReviewedAnswers          interface{} `json:"amountReviewedAnswers"`
	AmountCodeReviewMembers        interface{} `json:"amountCodeReviewMembers"`
	AmountCurrentCodeReviewMembers interface{} `json:"amountCurrentCodeReviewMembers"`
	GroupName                      string      `json:"groupName"`
	LocalCourseID                  *int64      `json:"localCourseId"`
	Typename                       string      `json:"__typename"`
}


func (ctx *RequestContext) GetRecommendedProjects(variables GetRecommendedProjects_Variables) (GetRecommendedProjects_Data, error) {
	request := gql.NewQueryRequest[GetRecommendedProjects_Variables](
		"query getRecommendedProjects($userId: ID!) {\n  student {\n    getRecommendedProjects(userId: $userId) {\n      ...StudentProjectItem\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment StudentProjectItem on StudentItem {\n  goalId\n  name\n  description\n  experience\n  dateTime\n  finalPercentage\n  laboriousness\n  executionType\n  goalStatus\n  courseType\n  displayedCourseStatus\n  amountAnswers\n  amountMembers\n  amountJoinedMembers\n  amountReviewedAnswers\n  amountCodeReviewMembers\n  amountCurrentCodeReviewMembers\n  groupName\n  localCourseId\n  __typename\n}\n",
		variables,
	)

	return GqlRequest[GetRecommendedProjects_Data](ctx, request)
}