/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetProjectStatistics_Variables struct {
	GoalID string `json:"goalId"`
}

type GetProjectStatistics_Data struct {
	Student GetProjectStatistics_Data_Student `json:"student"`
}

type GetProjectStatistics_Data_Student struct {
	GetProjectStatistics GetProjectStatistics_Data_GetProjectStatistics `json:"getProjectStatistics"`
	Typename             string                                         `json:"__typename"`
}

type GetProjectStatistics_Data_GetProjectStatistics struct {
	RegisteredStudents        int64                                            `json:"registeredStudents"`
	InProgressStudents        int64                                            `json:"inProgressStudents"`
	EvaluationStudents        int64                                            `json:"evaluationStudents"`
	FinishedStudents          int64                                            `json:"finishedStudents"`
	AcceptedStudents          int64                                            `json:"acceptedStudents"`
	FailedStudents            int64                                            `json:"failedStudents"`
	RetriedStudentsPercentage int64                                            `json:"retriedStudentsPercentage"`
	GroupProjectStatistics    GetProjectStatistics_Data_GroupProjectStatistics `json:"groupProjectStatistics"`
	Typename                  string                                           `json:"__typename"`
}

type GetProjectStatistics_Data_GroupProjectStatistics struct {
	InProgressTeams int64  `json:"inProgressTeams"`
	EvaluationTeams int64  `json:"evaluationTeams"`
	FinishedTeams   int64  `json:"finishedTeams"`
	AcceptedTeams   int64  `json:"acceptedTeams"`
	FailedTeams     int64  `json:"failedTeams"`
	Typename        string `json:"__typename"`
}

func (ctx *RequestContext) GetProjectStatistics(variables GetProjectStatistics_Variables) (GetProjectStatistics_Data, error) {
	request := gql.NewQueryRequest[GetProjectStatistics_Variables](
		"query getProjectStatistics($goalId: ID!) {\n  student {\n    getProjectStatistics(goalId: $goalId) {\n      ...ProjectStatistics\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment ProjectStatistics on ProjectStatistics {\n  registeredStudents\n  inProgressStudents\n  evaluationStudents\n  finishedStudents\n  acceptedStudents\n  failedStudents\n  retriedStudentsPercentage\n  groupProjectStatistics {\n    ...GroupProjectStatistics\n    __typename\n  }\n  __typename\n}\n\nfragment GroupProjectStatistics on GroupProjectStatistics {\n  inProgressTeams\n  evaluationTeams\n  finishedTeams\n  acceptedTeams\n  failedTeams\n  __typename\n}\n",
		variables,
	)

	return GqlRequest[GetProjectStatistics_Data](ctx, request)
}
