/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetProjectsWithOpenTeams_Variables struct {
}

type GetProjectsWithOpenTeams_Data struct {
	Student GetProjectsWithOpenTeams_Data_Student `json:"student"`
}

type GetProjectsWithOpenTeams_Data_Student struct {
	GetGroupProjectsWithOpenTeams []GetProjectsWithOpenTeams_Data_GetGroupProjectsWithOpenTeam `json:"getGroupProjectsWithOpenTeams"`
	Typename                      string                                                       `json:"__typename"`
}

type GetProjectsWithOpenTeams_Data_GetGroupProjectsWithOpenTeam struct {
	Module        GetProjectsWithOpenTeams_Data_Module      `json:"module"`
	CurrentTeam   GetProjectsWithOpenTeams_Data_CurrentTeam `json:"currentTeam"`
	InvitingTeams []interface{}                             `json:"invitingTeams"`
	Typename      string                                    `json:"__typename"`
}

type GetProjectsWithOpenTeams_Data_CurrentTeam struct {
	Team     GetProjectsWithOpenTeams_Data_Team     `json:"team"`
	Members  []GetProjectsWithOpenTeams_Data_Member `json:"members"`
	Typename string                                 `json:"__typename"`
}

type GetProjectsWithOpenTeams_Data_Member struct {
	User     GetProjectsWithOpenTeams_Data_User `json:"user"`
	Role     string                             `json:"role"`
	Typename string                             `json:"__typename"`
}

type GetProjectsWithOpenTeams_Data_User struct {
	ID                    string                                       `json:"id"`
	AvatarURL             string                                       `json:"avatarUrl"`
	Login                 string                                       `json:"login"`
	UserExperience        GetProjectsWithOpenTeams_Data_UserExperience `json:"userExperience"`
	ActiveSchoolShortName string                                       `json:"activeSchoolShortName"`
	Typename              string                                       `json:"__typename"`
}

type GetProjectsWithOpenTeams_Data_UserExperience struct {
	Level            GetProjectsWithOpenTeams_Data_Level `json:"level"`
	CookiesCount     int64                               `json:"cookiesCount"`
	CodeReviewPoints int64                               `json:"codeReviewPoints"`
	Typename         string                              `json:"__typename"`
}

type GetProjectsWithOpenTeams_Data_Level struct {
	ID        int64                               `json:"id"`
	LevelCode int64                               `json:"levelCode"`
	Range     GetProjectsWithOpenTeams_Data_Range `json:"range"`
	Typename  string                              `json:"__typename"`
}

type GetProjectsWithOpenTeams_Data_Range struct {
	LevelCode int64  `json:"levelCode"`
	Typename  string `json:"__typename"`
}

type GetProjectsWithOpenTeams_Data_Team struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Typename string `json:"__typename"`
}

type GetProjectsWithOpenTeams_Data_Module struct {
	ID                                string                                     `json:"id"`
	ModuleTitle                       string                                     `json:"moduleTitle"`
	OpenRegistration                  interface{}                                `json:"openRegistration"`
	StartProgress                     interface{}                                `json:"startProgress"`
	DurationFromStageSubjectGroupPlan int64                                      `json:"durationFromStageSubjectGroupPlan"`
	IsDeadlineFree                    bool                                       `json:"isDeadlineFree"`
	LocalCourseID                     interface{}                                `json:"localCourseId"`
	StudyModule                       GetProjectsWithOpenTeams_Data_StudyModule  `json:"studyModule"`
	SoftSkills                        []GetProjectsWithOpenTeams_Data_SoftSkill  `json:"softSkills"`
	TeamSettings                      GetProjectsWithOpenTeams_Data_TeamSettings `json:"teamSettings"`
	CurrentTask                       GetProjectsWithOpenTeams_Data_CurrentTask  `json:"currentTask"`
	Typename                          string                                     `json:"__typename"`
}

type GetProjectsWithOpenTeams_Data_CurrentTask struct {
	ID       string                             `json:"id"`
	Task     GetProjectsWithOpenTeams_Data_Task `json:"task"`
	Typename string                             `json:"__typename"`
}

type GetProjectsWithOpenTeams_Data_Task struct {
	StudentTaskAdditionalAttributes GetProjectsWithOpenTeams_Data_StudentTaskAdditionalAttributes `json:"studentTaskAdditionalAttributes"`
	Typename                        string                                                        `json:"__typename"`
}

type GetProjectsWithOpenTeams_Data_StudentTaskAdditionalAttributes struct {
	PointTask int64  `json:"pointTask"`
	Typename  string `json:"__typename"`
}

type GetProjectsWithOpenTeams_Data_SoftSkill struct {
	SoftSkillName    string  `json:"softSkillName"`
	SoftSkillID      int64   `json:"softSkillId"`
	TotalPower       int64   `json:"totalPower"`
	CurrentUserPower int64   `json:"currentUserPower"`
	MaxPower         int64   `json:"maxPower"`
	TeamRole         *string `json:"teamRole"`
	Typename         string  `json:"__typename"`
}

type GetProjectsWithOpenTeams_Data_StudyModule struct {
	Duration int64  `json:"duration"`
	Typename string `json:"__typename"`
}

type GetProjectsWithOpenTeams_Data_TeamSettings struct {
	MinAmountMember int64  `json:"minAmountMember"`
	MaxAmountMember int64  `json:"maxAmountMember"`
	Location        string `json:"location"`
	Typename        string `json:"__typename"`
}

func (ctx *RequestContext) GetProjectsWithOpenTeams(variables GetProjectsWithOpenTeams_Variables) (GetProjectsWithOpenTeams_Data, error) {
	request := gql.NewQueryRequest[GetProjectsWithOpenTeams_Variables](
		"query getProjectsWithOpenTeams {\n  student {\n    getGroupProjectsWithOpenTeams {\n      ...ProjectWithTeamInvitations\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment ProjectWithTeamInvitations on GroupProject {\n  module {\n    id\n    moduleTitle\n    openRegistration\n    startProgress\n    durationFromStageSubjectGroupPlan\n    isDeadlineFree\n    localCourseId\n    studyModule {\n      duration\n      __typename\n    }\n    softSkills {\n      ...SoftSkill\n      __typename\n    }\n    teamSettings {\n      minAmountMember\n      maxAmountMember\n      location\n      __typename\n    }\n    currentTask {\n      id\n      task {\n        studentTaskAdditionalAttributes {\n          pointTask\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  currentTeam {\n    ...CurrentTeamInvitationProject\n    __typename\n  }\n  invitingTeams {\n    ...InvitatingTeamsToProject\n    __typename\n  }\n  __typename\n}\n\nfragment SoftSkill on SoftSkillPoint {\n  softSkillName\n  softSkillId\n  totalPower\n  currentUserPower\n  maxPower\n  teamRole\n  __typename\n}\n\nfragment CurrentTeamInvitationProject on TeamWithMembers {\n  team {\n    id\n    name\n    __typename\n  }\n  members {\n    ...TeamMember\n    __typename\n  }\n  __typename\n}\n\nfragment TeamMember on TeamMember {\n  user {\n    ...TeamMemberUser\n    __typename\n  }\n  role\n  __typename\n}\n\nfragment TeamMemberUser on User {\n  id\n  avatarUrl\n  login\n  userExperience {\n    level {\n      id\n      levelCode\n      range {\n        levelCode\n        __typename\n      }\n      __typename\n    }\n    cookiesCount\n    codeReviewPoints\n    __typename\n  }\n  activeSchoolShortName\n  __typename\n}\n\nfragment InvitatingTeamsToProject on TeamWithMembers {\n  team {\n    id\n    name\n    currentTeamMemberCount\n    __typename\n  }\n  captains {\n    ...TeamMemberUser\n    __typename\n  }\n  __typename\n}\n",
		variables,
	)

	return GqlRequest[GetProjectsWithOpenTeams_Data](ctx, request)
}
