/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetProfileUser_Variables struct {
	UserID string `json:"userId"`
}

type GetProfileUser_Data struct {
	School21 GetProfileUser_Data_School21 `json:"school21"`
}

type GetProfileUser_Data_School21 struct {
	GetBasePublicProfile       GetProfileUser_Data_GetBasePublicProfile       `json:"getBasePublicProfile"`
	GetExperiencePublicProfile GetProfileUser_Data_GetExperiencePublicProfile `json:"getExperiencePublicProfile"`
	Typename                   string                                         `json:"__typename"`
}

type GetProfileUser_Data_GetBasePublicProfile struct {
	AvatarURL  string      `json:"avatarUrl"`
	FirstName  string      `json:"firstName"`
	MiddleName interface{} `json:"middleName"`
	LastName   string      `json:"lastName"`
	Typename   string      `json:"__typename"`
}

type GetProfileUser_Data_GetExperiencePublicProfile struct {
	ID               string                    `json:"id"`
	CookiesCount     int64                     `json:"cookiesCount"`
	CodeReviewPoints int64                     `json:"codeReviewPoints"`
	CoinsCount       int64                     `json:"coinsCount"`
	Level            GetProfileUser_Data_Level `json:"level"`
	Typename         string                    `json:"__typename"`
}

type GetProfileUser_Data_Level struct {
	ID       int64                     `json:"id"`
	Range    GetProfileUser_Data_Range `json:"range"`
	Typename string                    `json:"__typename"`
}

type GetProfileUser_Data_Range struct {
	ID        string `json:"id"`
	LevelCode int64  `json:"levelCode"`
	Typename  string `json:"__typename"`
}

func (ctx *RequestContext) GetProfileUser(variables GetProfileUser_Variables) (GetProfileUser_Data, error) {
	request := gql.NewQueryRequest[GetProfileUser_Variables](
		"query getProfileUser($userId: UUID!) {\n  school21 {\n    getBasePublicProfile(userId: $userId) {\n      avatarUrl\n      firstName\n      middleName\n      lastName\n      __typename\n    }\n    getExperiencePublicProfile(userId: $userId) {\n      ...CurrentUserExperience\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment CurrentUserExperience on UserExperience {\n  id\n  cookiesCount\n  codeReviewPoints\n  coinsCount\n  level {\n    id\n    range {\n      id\n      levelCode\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n",
		variables,
	)

	return GqlRequest[GetProfileUser_Data](ctx, request)
}
