/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetP2pReviewModeSettingsByStudentId_Variables struct {
	StudentID string `json:"studentId"`
}

type GetP2pReviewModeSettingsByStudentId_Data struct {
	School21 GetP2pReviewModeSettingsByStudentId_Data_School21 `json:"school21"`
}

type GetP2pReviewModeSettingsByStudentId_Data_School21 struct {
	GetP2PReviewModeSettingsByStudentID GetP2pReviewModeSettingsByStudentId_Data_GetP2PReviewModeSettingsByStudentID `json:"getP2pReviewModeSettingsByStudentId"`
	Typename                            string                                                                       `json:"__typename"`
}

type GetP2pReviewModeSettingsByStudentId_Data_GetP2PReviewModeSettingsByStudentID struct {
	Stage    GetP2pReviewModeSettingsByStudentId_Data_Stage `json:"stage"`
	Mode     string                                         `json:"mode"`
	Typename string                                         `json:"__typename"`
}

type GetP2pReviewModeSettingsByStudentId_Data_Stage struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Typename string `json:"__typename"`
}

func (ctx *RequestContext) GetP2pReviewModeSettingsByStudentId(variables GetP2pReviewModeSettingsByStudentId_Variables) (GetP2pReviewModeSettingsByStudentId_Data, error) {
	request := gql.NewQueryRequest[GetP2pReviewModeSettingsByStudentId_Variables](
		"query GetP2pReviewModeSettingsByStudentId($studentId: UUID!) {\n  school21 {\n    getP2pReviewModeSettingsByStudentId(studentId: $studentId) {\n      stage {\n        id\n        name\n        __typename\n      }\n      mode\n      __typename\n    }\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[GetP2pReviewModeSettingsByStudentId_Data](ctx, request)
}
