/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetToken_Variables struct {
}

type GetToken_Data struct {
	School21 GetToken_Data_School21 `json:"school21"`
}

type GetToken_Data_School21 struct {
	GenerateJwtTokenForCentrifugo string `json:"generateJwtTokenForCentrifugo"`
	Typename                      string `json:"__typename"`
}

func (ctx *RequestContext) GetToken(variables GetToken_Variables) (GetToken_Data, error) {
	request := gql.NewQueryRequest[GetToken_Variables](
		"query getToken {\n  school21 {\n    generateJwtTokenForCentrifugo\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[GetToken_Data](ctx, request)
}
