/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetCurrentUser_Variables struct {
}

type GetCurrentUser_Data struct {
	User GetCurrentUser_Data_User `json:"user"`
}

type GetCurrentUser_Data_User struct {
	GetCurrentUser GetCurrentUser_Data_GetCurrentUser `json:"getCurrentUser"`
	Typename       string                             `json:"__typename"`
}

type GetCurrentUser_Data_GetCurrentUser struct {
	ID                     string `json:"id"`
	AvatarURL              string `json:"avatarUrl"`
	Login                  string `json:"login"`
	FirstName              string `json:"firstName"`
	MiddleName             string `json:"middleName"`
	LastName               string `json:"lastName"`
	CurrentSchoolStudentID string `json:"currentSchoolStudentId"`
	Typename               string `json:"__typename"`
}

func (ctx *RequestContext) GetCurrentUser(variables GetCurrentUser_Variables) (GetCurrentUser_Data, error) {
	request := gql.NewQueryRequest[GetCurrentUser_Variables](
		"query getCurrentUser {\n  user {\n    getCurrentUser {\n      ...CurrentUser\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment CurrentUser on User {\n  id\n  avatarUrl\n  login\n  firstName\n  middleName\n  lastName\n  currentSchoolStudentId\n  __typename\n}\n",
		variables,
	)

	return GqlRequest[GetCurrentUser_Data](ctx, request)
}
