/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetUserNotificationsCount_Variables struct {
	WasReadIncluded bool `json:"wasReadIncluded"`
}


type GetUserNotificationsCount_Data struct {
	S21Notification GetUserNotificationsCount_Data_S21Notification `json:"s21Notification"`
}

type GetUserNotificationsCount_Data_S21Notification struct {
	GetS21NotificationsCount int64  `json:"getS21NotificationsCount"`
	Typename                 string `json:"__typename"`
}


func (ctx *RequestContext) GetUserNotificationsCount(variables GetUserNotificationsCount_Variables) (GetUserNotificationsCount_Data, error) {
	request := gql.NewQueryRequest[GetUserNotificationsCount_Variables](
		"query getUserNotificationsCount($wasReadIncluded: Boolean) {\n  s21Notification {\n    getS21NotificationsCount(wasReadIncluded: $wasReadIncluded)\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[GetUserNotificationsCount_Data](ctx, request)
}