/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetIsHonorRatingNeeded_Variables struct {
}

type GetIsHonorRatingNeeded_Data struct {
	HonorRating GetIsHonorRatingNeeded_Data_HonorRating `json:"honorRating"`
}

type GetIsHonorRatingNeeded_Data_HonorRating struct {
	IsHonorRatingNeeded bool   `json:"isHonorRatingNeeded"`
	Typename            string `json:"__typename"`
}

func (ctx *RequestContext) GetIsHonorRatingNeeded(variables GetIsHonorRatingNeeded_Variables) (GetIsHonorRatingNeeded_Data, error) {
	request := gql.NewQueryRequest[GetIsHonorRatingNeeded_Variables](
		"query getIsHonorRatingNeeded {\n  honorRating {\n    isHonorRatingNeeded\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[GetIsHonorRatingNeeded_Data](ctx, request)
}
