/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type GetPenaltiesCount_Variables struct {
	Statuses []string `json:"statuses"`
}

type GetPenaltiesCount_Data struct {
	Penalty GetPenaltiesCount_Data_Penalty `json:"penalty"`
}

type GetPenaltiesCount_Data_Penalty struct {
	CountMyPenalties int64  `json:"countMyPenalties"`
	Typename         string `json:"__typename"`
}

func (ctx *RequestContext) GetPenaltiesCount(variables GetPenaltiesCount_Variables) (GetPenaltiesCount_Data, error) {
	request := gql.NewQueryRequest[GetPenaltiesCount_Variables](
		"query getPenaltiesCount($statuses: [String]!) {\n  penalty {\n    countMyPenalties(statuses: $statuses)\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[GetPenaltiesCount_Data](ctx, request)
}
