/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import (
	"time"

	"github.com/arseniisemenow/s21auto-client-go/gql"
)

type ProjectMapGetStudentStateGraphNode_Variables struct {
	GraphNode ProjectMapGetStudentStateGraphNode_Variables_GraphNode `json:"graphNode"`
	StudentID string                                                 `json:"studentId"`
}

type ProjectMapGetStudentStateGraphNode_Variables_GraphNode struct {
	ID       string                                                `json:"id"`
	Label    string                                                `json:"label"`
	Handles  []string                                              `json:"handles"`
	Position ProjectMapGetStudentStateGraphNode_Variables_Position `json:"position"`
	Items    []ProjectMapGetStudentStateGraphNode_Variables_Item   `json:"items"`
	Typename string                                                `json:"__typename"`
}

type ProjectMapGetStudentStateGraphNode_Variables_Item struct {
	ID                string                                               `json:"id"`
	Code              string                                               `json:"code"`
	Handles           []string                                             `json:"handles"`
	EntityType        string                                               `json:"entityType"`
	EntityID          int64                                                `json:"entityId"`
	ParentNodeCodes   []string                                             `json:"parentNodeCodes"`
	ChildrenNodeCodes []string                                             `json:"childrenNodeCodes"`
	Skills            []interface{}                                        `json:"skills"`
	Goal              *ProjectMapGetStudentStateGraphNode_Variables_Course `json:"goal"`
	Course            *ProjectMapGetStudentStateGraphNode_Variables_Course `json:"course"`
	Typename          string                                               `json:"__typename"`
}

type ProjectMapGetStudentStateGraphNode_Variables_Course struct {
	ProjectID          int64   `json:"projectId"`
	ProjectName        string  `json:"projectName"`
	ProjectDescription string  `json:"projectDescription"`
	ProjectPoints      int64   `json:"projectPoints"`
	CourseType         *string `json:"courseType,omitempty"`
	IsMandatory        bool    `json:"isMandatory"`
	Typename           string  `json:"__typename"`
	GoalExecutionType  *string `json:"goalExecutionType,omitempty"`
}

type ProjectMapGetStudentStateGraphNode_Variables_Position struct {
	X        int64  `json:"x"`
	Y        int64  `json:"y"`
	Typename string `json:"__typename"`
}

type ProjectMapGetStudentStateGraphNode_Data struct {
	HolyGraph ProjectMapGetStudentStateGraphNode_Data_HolyGraph `json:"holyGraph"`
}

type ProjectMapGetStudentStateGraphNode_Data_HolyGraph struct {
	GetStudentStateGraphNode ProjectMapGetStudentStateGraphNode_Data_GetStudentStateGraphNode `json:"getStudentStateGraphNode"`
	Typename                 string                                                           `json:"__typename"`
}

type ProjectMapGetStudentStateGraphNode_Data_GetStudentStateGraphNode struct {
	ID       string                                         `json:"id"`
	Items    []ProjectMapGetStudentStateGraphNode_Data_Item `json:"items"`
	Typename string                                         `json:"__typename"`
}

type ProjectMapGetStudentStateGraphNode_Data_Item struct {
	ID       string                                          `json:"id"`
	Goal     *ProjectMapGetStudentStateGraphNode_Data_Course `json:"goal"`
	Course   *ProjectMapGetStudentStateGraphNode_Data_Course `json:"course"`
	Typename string                                          `json:"__typename"`
}

type ProjectMapGetStudentStateGraphNode_Data_Course struct {
	ProjectState  string     `json:"projectState"`
	LocalCourseID *int64     `json:"localCourseId,omitempty"`
	Duration      int64      `json:"duration"`
	ProjectDate   *time.Time `json:"projectDate"`
	Typename      string     `json:"__typename"`
}

func (ctx *RequestContext) ProjectMapGetStudentStateGraphNode(variables ProjectMapGetStudentStateGraphNode_Variables) (ProjectMapGetStudentStateGraphNode_Data, error) {
	request := gql.NewQueryRequest[ProjectMapGetStudentStateGraphNode_Variables](
		"query ProjectMapGetStudentStateGraphNode($graphNode: JsonNode!, $studentId: UUID, $stageGroupId: Int) {\n  holyGraph {\n    getStudentStateGraphNode(\n      graphNode: $graphNode\n      studentId: $studentId\n      stageGroupId: $stageGroupId\n    ) {\n      id\n      items {\n        id\n        goal {\n          projectState\n          duration\n          projectDate\n          __typename\n        }\n        course {\n          projectState\n          localCourseId\n          duration\n          projectDate\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[ProjectMapGetStudentStateGraphNode_Data](ctx, request)
}
