/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type ProjectMapGetStudentStageGroups_Variables struct {
	StudentID string `json:"studentId"`
}

type ProjectMapGetStudentStageGroups_Data struct {
	School21 ProjectMapGetStudentStageGroups_Data_School21 `json:"school21"`
}

type ProjectMapGetStudentStageGroups_Data_School21 struct {
	LoadStudentStageGroups []ProjectMapGetStudentStageGroups_Data_LoadStudentStageGroup `json:"loadStudentStageGroups"`
	Typename               string                                                       `json:"__typename"`
}

type ProjectMapGetStudentStageGroups_Data_LoadStudentStageGroup struct {
	StudentID           string                                             `json:"studentId"`
	StageGroupStudentID string                                             `json:"stageGroupStudentId"`
	StageGroupS21       ProjectMapGetStudentStageGroups_Data_StageGroupS21 `json:"stageGroupS21"`
	Typename            string                                             `json:"__typename"`
}

type ProjectMapGetStudentStageGroups_Data_StageGroupS21 struct {
	WaveID   int64  `json:"waveId"`
	WaveName string `json:"waveName"`
	EduForm  string `json:"eduForm"`
	Active   bool   `json:"active"`
	Typename string `json:"__typename"`
}

func (ctx *RequestContext) ProjectMapGetStudentStageGroups(variables ProjectMapGetStudentStageGroups_Variables) (ProjectMapGetStudentStageGroups_Data, error) {
	request := gql.NewQueryRequest[ProjectMapGetStudentStageGroups_Variables](
		"query ProjectMapGetStudentStageGroups($studentId: UUID!) {\n  school21 {\n    loadStudentStageGroups(studentId: $studentId) {\n      studentId\n      stageGroupStudentId\n      stageGroupS21 {\n        waveId\n        waveName\n        eduForm\n        active\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[ProjectMapGetStudentStageGroups_Data](ctx, request)
}
