/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type ProjectMapGetStudentGraphTemplate_Variables struct {
	StudentID string `json:"studentId"`
}

type ProjectMapGetStudentGraphTemplate_Data struct {
	HolyGraph ProjectMapGetStudentGraphTemplate_Data_HolyGraph `json:"holyGraph"`
}

type ProjectMapGetStudentGraphTemplate_Data_HolyGraph struct {
	GetStudentGraphTemplate ProjectMapGetStudentGraphTemplate_Data_GetStudentGraphTemplate `json:"getStudentGraphTemplate"`
	Typename                string                                                         `json:"__typename"`
}

type ProjectMapGetStudentGraphTemplate_Data_GetStudentGraphTemplate struct {
	Edges    []ProjectMapGetStudentGraphTemplate_Data_Edge `json:"edges"`
	Nodes    []ProjectMapGetStudentGraphTemplate_Data_Node `json:"nodes"`
	Typename string                                        `json:"__typename"`
}

type ProjectMapGetStudentGraphTemplate_Data_Edge struct {
	ID           string                                           `json:"id"`
	Source       string                                           `json:"source"`
	Target       string                                           `json:"target"`
	SourceHandle string                                           `json:"sourceHandle"`
	TargetHandle string                                           `json:"targetHandle"`
	Data         ProjectMapGetStudentGraphTemplate_Data_DataClass `json:"data"`
	Typename     string                                           `json:"__typename"`
}

type ProjectMapGetStudentGraphTemplate_Data_DataClass struct {
	SourceGap int64                                             `json:"sourceGap"`
	TargetGap int64                                             `json:"targetGap"`
	Points    []ProjectMapGetStudentGraphTemplate_Data_Position `json:"points"`
	Typename  string                                            `json:"__typename"`
}

type ProjectMapGetStudentGraphTemplate_Data_Position struct {
	X        int64  `json:"x"`
	Y        int64  `json:"y"`
	Typename string `json:"__typename"`
}

type ProjectMapGetStudentGraphTemplate_Data_Node struct {
	ID       string                                          `json:"id"`
	Label    string                                          `json:"label"`
	Handles  []string                                        `json:"handles"`
	Position ProjectMapGetStudentGraphTemplate_Data_Position `json:"position"`
	Items    []ProjectMapGetStudentGraphTemplate_Data_Item   `json:"items"`
	Typename string                                          `json:"__typename"`
}

type ProjectMapGetStudentGraphTemplate_Data_Item struct {
	ID                string                                         `json:"id"`
	Code              string                                         `json:"code"`
	Handles           []string                                       `json:"handles"`
	EntityType        string                                         `json:"entityType"`
	EntityID          int64                                          `json:"entityId"`
	ParentNodeCodes   []string                                       `json:"parentNodeCodes"`
	ChildrenNodeCodes []string                                       `json:"childrenNodeCodes"`
	Skills            []interface{}                                  `json:"skills"`
	Goal              *ProjectMapGetStudentGraphTemplate_Data_Course `json:"goal"`
	Course            *ProjectMapGetStudentGraphTemplate_Data_Course `json:"course"`
	Typename          string                                         `json:"__typename"`
}

type ProjectMapGetStudentGraphTemplate_Data_Course struct {
	ProjectID          int64   `json:"projectId"`
	ProjectName        string  `json:"projectName"`
	ProjectDescription string  `json:"projectDescription"`
	ProjectPoints      int64   `json:"projectPoints"`
	CourseType         *string `json:"courseType,omitempty"`
	IsMandatory        bool    `json:"isMandatory"`
	Typename           string  `json:"__typename"`
	GoalExecutionType  *string `json:"goalExecutionType,omitempty"`
}

func (ctx *RequestContext) ProjectMapGetStudentGraphTemplate(variables ProjectMapGetStudentGraphTemplate_Variables) (ProjectMapGetStudentGraphTemplate_Data, error) {
	request := gql.NewQueryRequest[ProjectMapGetStudentGraphTemplate_Variables](
		"query ProjectMapGetStudentGraphTemplate($studentId: UUID, $stageGroupId: Int) {\n  holyGraph {\n    getStudentGraphTemplate(studentId: $studentId, stageGroupId: $stageGroupId) {\n      edges {\n        id\n        source\n        target\n        sourceHandle\n        targetHandle\n        data {\n          sourceGap\n          targetGap\n          points {\n            x\n            y\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      nodes {\n        id\n        label\n        handles\n        position {\n          x\n          y\n          __typename\n        }\n        items {\n          id\n          code\n          handles\n          entityType\n          entityId\n          parentNodeCodes\n          childrenNodeCodes\n          skills {\n            id\n            name\n            color\n            textColor\n            __typename\n          }\n          goal {\n            projectId\n            projectName\n            projectDescription\n            projectPoints\n            goalExecutionType\n            isMandatory\n            __typename\n          }\n          course {\n            projectId\n            projectName\n            projectDescription\n            projectPoints\n            courseType\n            isMandatory\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[ProjectMapGetStudentGraphTemplate_Data](ctx, request)
}
