/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type PublicProfileGetProjectsStatuses_Variables struct {
	StudentID string                                               `json:"studentId"`
	Projects  []PublicProfileGetProjectsStatuses_Variables_Project `json:"projects"`
}

type PublicProfileGetProjectsStatuses_Variables_Project struct {
	GoalID        *int64 `json:"goalId"`
	LocalCourseID *int64 `json:"localCourseId"`
}

type PublicProfileGetProjectsStatuses_Data struct {
	School21 PublicProfileGetProjectsStatuses_Data_School21 `json:"school21"`
}

type PublicProfileGetProjectsStatuses_Data_School21 struct {
	GetStudentProjectStatusesForPublicProfileV2 []PublicProfileGetProjectsStatuses_Data_GetStudentProjectStatusesForPublicProfileV2 `json:"getStudentProjectStatusesForPublicProfileV2"`
	Typename                                    string                                                                              `json:"__typename"`
}

type PublicProfileGetProjectsStatuses_Data_GetStudentProjectStatusesForPublicProfileV2 struct {
	GroupName             string  `json:"groupName"`
	Name                  string  `json:"name"`
	Experience            int64   `json:"experience"`
	FinalPercentage       *int64  `json:"finalPercentage"`
	GoalID                *int64  `json:"goalId"`
	GoalStatus            *string `json:"goalStatus"`
	AmountAnswers         *int64  `json:"amountAnswers"`
	AmountReviewedAnswers *int64  `json:"amountReviewedAnswers"`
	ExecutionType         *string `json:"executionType"`
	LocalCourseID         *int64  `json:"localCourseId"`
	CourseType            *string `json:"courseType"`
	DisplayedCourseStatus *string `json:"displayedCourseStatus"`
	Typename              string  `json:"__typename"`
}

func (ctx *RequestContext) PublicProfileGetProjectsStatuses(variables PublicProfileGetProjectsStatuses_Variables) (PublicProfileGetProjectsStatuses_Data, error) {
	request := gql.NewQueryRequest[PublicProfileGetProjectsStatuses_Variables](
		"query publicProfileGetProjectsStatuses($studentId: UUID!, $projects: [StudentItemEntityInput!]!) {\n  school21 {\n    getStudentProjectStatusesForPublicProfileV2(\n      studentId: $studentId\n      projects: $projects\n    ) {\n      groupName\n      name\n      experience\n      finalPercentage\n      goalId\n      goalStatus\n      amountAnswers\n      amountReviewedAnswers\n      executionType\n      localCourseId\n      courseType\n      displayedCourseStatus\n      __typename\n    }\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[PublicProfileGetProjectsStatuses_Data](ctx, request)
}
