/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type PublicProfileGetAchievements_Variables struct {
	UserID string `json:"userId"`
}


type PublicProfileGetAchievements_Data struct {
	School21 PublicProfileGetAchievements_Data_School21 `json:"school21"`
}

type PublicProfileGetAchievements_Data_School21 struct {
	GetBadgesPublicProfile []PublicProfileGetAchievements_Data_GetBadgesPublicProfile `json:"getBadgesPublicProfile"`
	Typename               string                   `json:"__typename"`
}

type PublicProfileGetAchievements_Data_GetBadgesPublicProfile struct {
	Points   int64  `json:"points"`
	ID       string `json:"id"`
	Badge    PublicProfileGetAchievements_Data_Badge  `json:"badge"`
	Typename string `json:"__typename"`
}

type PublicProfileGetAchievements_Data_Badge struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	AvatarURL string `json:"avatarUrl"`
	Typename  string `json:"__typename"`
}


func (ctx *RequestContext) PublicProfileGetAchievements(variables PublicProfileGetAchievements_Variables) (PublicProfileGetAchievements_Data, error) {
	request := gql.NewQueryRequest[PublicProfileGetAchievements_Variables](
		"query publicProfileGetAchievements($userId: UUID!) {\n  school21 {\n    getBadgesPublicProfile(userId: $userId) {\n      points\n      id\n      badge {\n        id\n        name\n        avatarUrl\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[PublicProfileGetAchievements_Data](ctx, request)
}