/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type PublicProfileLoadStageGroups_Variables struct {
	StudentID string `json:"studentId"`
}

type PublicProfileLoadStageGroups_Data struct {
	School21 PublicProfileLoadStageGroups_Data_School21 `json:"school21"`
}

type PublicProfileLoadStageGroups_Data_School21 struct {
	LoadStudentStageGroups []PublicProfileLoadStageGroups_Data_LoadStudentStageGroup `json:"loadStudentStageGroups"`
	Typename               string                                                    `json:"__typename"`
}

type PublicProfileLoadStageGroups_Data_LoadStudentStageGroup struct {
	StageGroupStudentID string                                          `json:"stageGroupStudentId"`
	StudentID           string                                          `json:"studentId"`
	StageGroupS21       PublicProfileLoadStageGroups_Data_StageGroupS21 `json:"stageGroupS21"`
	SafeSchool          PublicProfileLoadStageGroups_Data_SafeSchool    `json:"safeSchool"`
	Typename            string                                          `json:"__typename"`
}

type PublicProfileLoadStageGroups_Data_SafeSchool struct {
	FullName string `json:"fullName"`
	Typename string `json:"__typename"`
}

type PublicProfileLoadStageGroups_Data_StageGroupS21 struct {
	WaveID   int64  `json:"waveId"`
	WaveName string `json:"waveName"`
	EduForm  string `json:"eduForm"`
	Active   bool   `json:"active"`
	Typename string `json:"__typename"`
}

func (ctx *RequestContext) PublicProfileLoadStageGroups(variables PublicProfileLoadStageGroups_Variables) (PublicProfileLoadStageGroups_Data, error) {
	request := gql.NewQueryRequest[PublicProfileLoadStageGroups_Variables](
		"query publicProfileLoadStageGroups($studentId: UUID!) {\n  school21 {\n    loadStudentStageGroups(studentId: $studentId) {\n      stageGroupStudentId\n      studentId\n      stageGroupS21 {\n        waveId\n        waveName\n        eduForm\n        active\n        __typename\n      }\n      safeSchool {\n        fullName\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[PublicProfileLoadStageGroups_Data](ctx, request)
}
