/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type PublicProfileGetProjects_Variables struct {
	StudentID    string `json:"studentId"`
	StageGroupID string `json:"stageGroupId"`
}

type PublicProfileGetProjects_Data struct {
	School21 PublicProfileGetProjects_Data_School21 `json:"school21"`
}

type PublicProfileGetProjects_Data_School21 struct {
	GetStudentProjectsForPublicProfileV2 []PublicProfileGetProjects_Data_GetStudentProjectsForPublicProfileV2 `json:"getStudentProjectsForPublicProfileV2"`
	Typename                             string                                                               `json:"__typename"`
}

type PublicProfileGetProjects_Data_GetStudentProjectsForPublicProfileV2 struct {
	GroupName             string      `json:"groupName"`
	Name                  string      `json:"name"`
	Experience            int64       `json:"experience"`
	FinalPercentage       int64       `json:"finalPercentage"`
	GoalID                *int64      `json:"goalId"`
	GoalStatus            interface{} `json:"goalStatus"`
	AmountAnswers         interface{} `json:"amountAnswers"`
	AmountReviewedAnswers interface{} `json:"amountReviewedAnswers"`
	ExecutionType         *string     `json:"executionType"`
	LocalCourseID         *int64      `json:"localCourseId"`
	CourseType            *string     `json:"courseType"`
	DisplayedCourseStatus interface{} `json:"displayedCourseStatus"`
	Typename              string      `json:"__typename"`
}

func (ctx *RequestContext) PublicProfileGetProjects(variables PublicProfileGetProjects_Variables) (PublicProfileGetProjects_Data, error) {
	request := gql.NewQueryRequest[PublicProfileGetProjects_Variables](
		"query publicProfileGetProjects($studentId: UUID!, $stageGroupId: ID!) {\n  school21 {\n    getStudentProjectsForPublicProfileV2(\n      studentId: $studentId\n      stageGroupId: $stageGroupId\n    ) {\n      groupName\n      name\n      experience\n      finalPercentage\n      goalId\n      goalStatus\n      amountAnswers\n      amountReviewedAnswers\n      executionType\n      localCourseId\n      courseType\n      displayedCourseStatus\n      __typename\n    }\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[PublicProfileGetProjects_Data](ctx, request)
}
