/*
This file was generated by s21auto (https://github.com/s21toolkit/s21auto) and is not intended for manual editing.
*/
package requests

import "github.com/arseniisemenow/s21auto-client-go/gql"

type StudentProfileGetUserRestrictionsByUserIdAndSchoolId_Variables struct {
	UserID   string `json:"userId"`
	SchoolID string `json:"schoolId"`
}

type StudentProfileGetUserRestrictionsByUserIdAndSchoolId_Data struct {
	School21 StudentProfileGetUserRestrictionsByUserIdAndSchoolId_Data_School21 `json:"school21"`
}

type StudentProfileGetUserRestrictionsByUserIdAndSchoolId_Data_School21 struct {
	GetUserRestrictionsByUserIDAndSchoolID []interface{} `json:"getUserRestrictionsByUserIdAndSchoolId"`
	Typename                               string        `json:"__typename"`
}

func (ctx *RequestContext) StudentProfileGetUserRestrictionsByUserIdAndSchoolId(variables StudentProfileGetUserRestrictionsByUserIdAndSchoolId_Variables) (StudentProfileGetUserRestrictionsByUserIdAndSchoolId_Data, error) {
	request := gql.NewQueryRequest[StudentProfileGetUserRestrictionsByUserIdAndSchoolId_Variables](
		"query StudentProfileGetUserRestrictionsByUserIdAndSchoolId($userId: UUID!, $schoolId: UUID!) {\n  school21 {\n    getUserRestrictionsByUserIdAndSchoolId(userId: $userId, schoolId: $schoolId) {\n      restrictionId\n      restrictionType\n      userId\n      schoolId\n      isActive\n      createdTs\n      updatedTs\n      __typename\n    }\n    __typename\n  }\n}\n",
		variables,
	)

	return GqlRequest[StudentProfileGetUserRestrictionsByUserIdAndSchoolId_Data](ctx, request)
}
